### PR TITLE
Added mapping for tracker_id.

### PR DESCRIPTION
**Pull request by stoffus**

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Thanks

**Comment by PowerKiKi** [comment]
Would you mind telling on what version of Redmine you used this tool, please ?

**Comment by stoffus** [comment]
Sure, I migrated between 2.3.2.devel and 2.5.2.devel.

**Comment by PowerKiKi** [comment]
Thanks for the info! I was wondering if it still worked on 3.0 branch...

**Pull request merged**
